# -*- coding: utf-8 -*-
"""Assignmnt 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dFupfKJcmB92RONrDBFRYZEzRfDiDFMI

Question 1:
"""

a=int(input("Enter no:"))
d={1:1}
for i in range(1,a+1):
  d.update({i:i*i})
print(d)

"""Question 2:"""

list_1=[]
for i in range(1,51):
  list_1.append(i)
print(list_1);
a,b=input("Enter to no's:").split();
a=int(a);
b=int(b);
for i in list_1:
  if a<i<=b:
    print(i)
  if i>b:
    break;