# -*- coding: utf-8 -*-
"""Assignment 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15qPtqtZzIEOvnsELUgnuCMpjxrGRM5OB
"""

str=input("Enter number's seperated by  :")
print(str)
q=['1','1','5']
s =  all(elem in str  for elem in q);
if s:
    print("It's a Match")
else:
    print("It's gone")